main: A Basic Workflow

on: push

jobs:
  # jobs require job IDs (job1, job2)
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      # ' - ' defines a step and the 'name' is optional
      - name: Step One
        uses: actions/checkout@v4 # This is a function that takes this repository and bundles it up and brings it to the machine (ubuntu-latest)
      - name: Step Two
        run: ls -la
      - run: pwd # Here, we did not name the step as naming it is optional

  job2:
    name: Second job to run
    runs-on: windows-latest # This is a function that takes this repository and bundles it up and brings it to the machine (windows-latest)
    steps:
      - name: Step One of job2
        uses: actions/checkout@v4
      - name: Step Two of job2
        run: pwd
